language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          - libsdl2-dev
    - os: osx
      addons:
        homebrew:
          packages:
            - sdl2

script:
- cd src
- make
