  
language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      before_install:
        - sudo apt update
        - sudo apt install libsdl2-dev
    - os: osx
      before_install:
        - brew update
        - brew install sdl2
     

script:
- cd test
- make
- ./test
- cd ..
- make
