  
language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      before_install:
        - sudo apt update
        - sudo apt install libsdl2-dev

script:
- cd test
- make
- ./test
- cd ../src
- make
