language: cpp

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

sudo: required

addons:
  apt:
    packages:
      libsdl2-dev

before-install:
  - if ["$TRAVIS_OS_NAME" = "osx"]; then brew update; fi
  - if ["$TRAVIS_OS_NAME" = "osx"]; then brew install sdl2; fi

script:
- cd src
- make
