  
language: cpp

matrix:
  include:
    - os: linux
      arch: arm64
      sudo: required
      before_install:
        - sudo apt update
        - sudo apt install libsdl2-dev
    - os: linux
      arch: amd64
      sudo: required
      before_install:
        - sudo apt update
        - sudo apt install libsdl2-dev
    - os: osx
      before_install:
        - brew update
        - brew install sdl2
    
script:
- cd test
- make
- ./test
- cd ..
- make


deploy:
  provider: releases
  api_key: $GITHUB_OATH
  file: "cosmic"
  skip_cleanup: true
  on:
    tags: true

