language: cpp

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang

sudo: required

addons:
  apt:
    packages: libsdl2-dev
    
    
script:
- if [$TRAVIS_OS_NAME=osx]; then brew install sdl2;
- cd src
- make
