language: cpp

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

sudo: required

addons:
  apt:
    packages:
      - libsdl2-dev
  homebrew:
    packages:
      - sdl2
      update: true

script:
- cd src
- make
